# Site settings
title: Ibrahim Alaybeyi
url: "https://alaybeyi.net"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Europe/Istanbul
description: >
  The my blog page

# Your information
email: ibrahim@alaybeyi.net
author: Ibrahim Alaybeyi	
avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: Computer Scientist - Free Software Advocate - Security & Privacy Searcher
twitter_username: ibrahimalaybeyi
github_username:  alaybey

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
